### ISSUE TITLE
Problem with Installing 

### ISSUE THREAD

**Issue by samigonza3** [dgnsrekt/nitter_scraper#11]
Hi, I just got this triying to install the library via PIP. What can I do?

ERROR: Cannot install nitter_scraper because these package versions have conflicting dependencies.

The conflict is caused by:
    docker 4.4.4 depends on pywin32==227; sys_platform == "win32"
    docker 4.4.3 depends on pywin32==227; sys_platform == "win32"
    docker 4.4.2 depends on pywin32==227; sys_platform == "win32"
    docker 4.4.1 depends on pywin32==227; sys_platform == "win32"
    docker 4.4.0 depends on pywin32==227; sys_platform == "win32"
    docker 4.3.1 depends on pywin32==227; sys_platform == "win32"

**Comment by ewebgh33** [comment]
@samigonza3 

I had this error today, I set up an env with 3.11.
Then saw in the files, one of them mentioned python 3.7 or 3.8. So I removed the conda env and set up a new one with python=3.8.

This solved the error and I was able to continue on. Hope this helps.
